### ISSUE TITLE
Stop pedometer UI from going over maxStepCount

### ISSUE THREAD

**Issue by cherrybeans** [ywj7373/MC-group2#138]
I frequently see the pedometer from going over the max limit and shows things such as 13 of 10 steps. Does not look good. Only the UI matters, what happens behind the scenes doesn't matter as 13 of 10 steps is as good of a reason to unblock as 10 of 10 steps.

**What** Fix UI so that it doesn't exceed the max step count.

![Screenshot_20191205-073615_BlueCatApp](https://user-images.githubusercontent.com/25204035/70189490-cb9da300-1736-11ea-99a1-7837424b1763.jpg)

**Comment by rachelg98** [comment]
I think this might be related to receiving live data updates too. The step count is updated in the AppBlocking fragment and when the app is unblocked the fragment isn't notified of the update unless you reload the fragment.
But I'll set an upper bound on the step counter in the mean time. Thanks for raising the issue :)
